### ISSUE TITLE
Original Switchmate confirmed working

### ISSUE THREAD

**Issue by C2BB** [deatondg/Switchmate-ESPHome#2]
Thank you for this wonderful solution! I used it on a $4 HiLetGo ESP32-CAM to connect to an original Switchmate. After a while of ignorantly trying to follow steps 2-4 as a home-assistant custom component rather than an ESPHome custom component (that was already done in the example yaml) I was up and running in HA. I was having erratic response and doubled the polling to 2000 and it's been working perfectly since. 

No issues to report, just wanted to share :)

**Comment by deatondg** [comment]
Thank you for the positive feedback! I don't share code often, so I'm really glad to hear my work was helpful to someone. :)

Feel free to reach out again if you have any issues, suggestions, or improvements!
